services:
  postgres:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    container_name: fiscal_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fiscal_data}
      POSTGRES_USER: ${POSTGRES_USER:-fiscal_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - fiscal_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fiscal_user} -d ${POSTGRES_DB:-fiscal_data}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - fiscal_network

  bot:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: fiscal_bot
    environment:
      # Настройки базы данных
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-fiscal_data}
      POSTGRES_USER: ${POSTGRES_USER:-fiscal_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_123}
      DATABASE_URL: postgresql://${POSTGRES_USER:-fiscal_user}:${POSTGRES_PASSWORD:-secure_password_123}@postgres:5432/${POSTGRES_DB:-fiscal_data}

      # Настройки Telegram бота
      TG_TOKEN: ${TG_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      
      # Настройки Python
      PYTHONPATH: /app/src
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./log:/app/log
    networks:
      - fiscal_network

networks:
  fiscal_network:
    driver: bridge

volumes:
  fiscal_postgres_data:
    driver: local
